### PR TITLE
Fix use of strchr with new GCC

### PR DESCRIPTION
**Pull request by abbra**
According to C specification, 7.28.5.1, strchr() is a generic function and its string argument's type is promoted to the result. So if it is const char*, the result will be const char* as well.

gcc in Rawhide (15.2.1 20251111) implements this conformance, resulting in a compilation fail with -Werror=discarded-qualifiers.

We either have to change target variable definition to be 'const char *' or cast the argument to 'char *'.

### CODE REVIEW

**Comment by abbra** [comment]
Sample of a failed build (scroll to the end): https://kojipkgs.fedoraproject.org//work/tasks/9032/139609032/build.log

```
making all in lib/krb5/ccache...
make[3]: Entering directory '/builddir/build/BUILD/krb5-1.21.3-build/krb5-1.21.3/src/lib/krb5/ccache'
gcc -fPIC -DSHARED -DHAVE_CONFIG_H  -I../../../include -I../../../include -I./ccapi -I. -I. -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE -I/usr/include/et -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -I/usr/include/et -fPIC -fno-strict-aliasing -fstack-protector-all -Wall -Wcast-align -Wshadow -Wmissing-prototypes -Wno-format-zero-length -Woverflow -Wstrict-overflow -Wmissing-format-attribute -Wmissing-prototypes -Wreturn-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wsign-compare -Werror=uninitialized -Wno-maybe-uninitialized -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=discarded-qualifiers -Werror=implicit-int -Werror=strict-prototypes -Werror=declaration-after-statement -Werror-implicit-function-declaration -pthread  -c ccbase.c -o ccbase.so.o && mv -f ccbase.so.o ccbase.so
ccbase.c: In function ‘krb5_cc_resolve’:
ccbase.c:213:8: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  213 |     cp = strchr (name, ':');
      |        ^
cc1: some warnings being treated as errors
make[3]: *** [Makefile:787: ccbase.so] Error 1
make[3]: Leaving directory '/builddir/build/BUILD/krb5-1.21.3-build/krb5-1.21.3/src/lib/krb5/ccache'
make[2]: *** [Makefile:1113: all-recurse] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/krb5-1.21.3-build/krb5-1.21.3/src/lib/krb5'
make[1]: *** [Makefile:974: all-recurse] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/krb5-1.21.3-build/krb5-1.21.3/src/lib'
make: *** [Makefile:1520: all-recurse] Error 1
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.QM3hsw (%build)
    Bad exit status from /var/tmp/rpm-tmp.QM3hsw (%build)
Child return code was: 1
```

**Comment by abbra** [comment]
C specification draft that can be used to view section 7.28.5.1: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3685.pdf

**Comment by jrisc** [comment]
I think there should be no cast on the input string parameter of `strchr()` to discard the `const` qualifier. This will likely result in the original string to be modified via the returned pointer. This is the case in the `parse_uri_if_https()` function where `cp` is used to write a null terminator in the string originally provided by the `host_or_uri` argument which is supposed to point to an immutable string. In such case, it means that the signature of the function is wrong, and the problem should be addressed at this level.

I reworked this commit to create a test patch for Fedora Rawhide with additional changes in order not to use casts (it builds successfully):
https://src.fedoraproject.org/rpms/krb5/pull-request/69

**Comment by abbra** [comment]
Thanks, I've updated the patchset.

**Comment by abbra** [comment]
@greghudson there is a typo in the rewritten commit message, 7.26.5.1 instead of 7.28.5.1. Section 7.26 only has three subsections.

**Comment by greghudson** [comment]
What document are you looking at?  I found https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf and it has strchr in 7.26.5.3; section 7.28 there is <threads.h>.

(Looking back I see you gave a link already; I will check that out and compare.)

**Comment by greghudson** [comment]
Okay, I assume n3685 is newer than n3096 just based on the number.  I had found <https://www.reddit.com/r/C_Programming/comments/w5hl80/c23_now_finalized/> which I guess wasn't reliable.  I will change the reference in the commit message back to 7.28.

**Comment by abbra** [comment]
Yes, I used n3685, as commented with the link earlier in this thread

**Comment by jrisc** [comment]
There is another case in `tests/responder.c`:
```
responder.c: In function ‘responder’:
responder.c:285:17: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  285 |             key = strchr(data->otp_answer, '=');
      |                 ^
```

It can be fixed this way:
```diff
index 82f870ea5d..4221a20283 100644
--- a/src/tests/responder.c
+++ b/src/tests/responder.c
@@ -282,8 +282,7 @@ responder(krb5_context ctx, void *rawdata, krb5_responder_context rctx)
     /* Provide a particular response for an OTP challenge. */
     if (data->otp_answer != NULL) {
         if (krb5_responder_otp_get_challenge(ctx, rctx, &ochl) == 0) {
-            key = strchr(data->otp_answer, '=');
-            if (key != NULL) {
+            if (strchr(data->otp_answer, '=') != NULL) {
                 /* Make a copy of the answer that we can chop up. */
                 key = strdup(data->otp_answer);
                 if (key == NULL)
```

**Comment by avivanoff** [comment]
Since this change is not in 1.22.2, it fails to compile on Ubuntu 26, GCC 15.2 (probably other platforms as well). Are you planning a release with this fix in?
